//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTable
    {
        public int id { get; set; }
        public Nullable<int> ClientID { get; set; }
        public int SellersID { get; set; }
        public int CarID { get; set; }
        public int CurrentPrice { get; set; }
    
        public virtual CarsTable CarsTable { get; set; }
        public virtual ClientsTable ClientsTable { get; set; }
        public virtual SellersTable SellersTable { get; set; }
    }
}
